### ISSUE TITLE
Connecting announcement link on class cards to announcement modal

### ISSUE THREAD

**Issue by nik98hil** [siddhantvinchurkar/Omega#12]
The announcement links on the class cards should trigger the announcement modal where only the announcements of that particular class should be pulled from the database.
<img width="631" alt="capture" src="https://user-images.githubusercontent.com/40880699/45263607-c70e1000-b449-11e8-9d8b-b05acd176747.PNG">

**Comment by siddhantvinchurkar** [comment]
Add a screenshot for convenience, please.
