### ISSUE TITLE
The navigation drawer trigger appears before the website loads

### ISSUE THREAD

**Issue by siddhantvinchurkar** [siddhantvinchurkar/Omega#5]
### In fact, try to make the logo in the top left corner trigger it
![Fix the navigation drawer trigger](https://u.imageresize.org/v2/6915c6d6-fb63-4bd9-a9bf-34ebd5b8890e.png "Fix the navigation drawer trigger")

**Comment by nik98hil** [comment]
Shoved the drag trigger into the logo
